name: Release
description: Push and release artifact.
inputs:
  artifact:
    default: viewer.tar.gz
  comment:
    default: GitHub Actions
  user-email:
    default: actions@github.com
  user-name:
    default: GitHub Actions
runs:
  using: composite
  steps:
    - shell: sh
      run: |
        echo "tag=`date +${{ github.ref_name }}-%Y.%m.%d-%H.%M.%S`" >> $GITHUB_ENV
        git config --global user.name "${{ inputs.user-name }}"
        git config --global user.email "${{ inputs.user-email }}"
        git tag -a ${{ env.tag }} -m "${{ inputs.comment }}"
        git push origin ${{ env.tag }}
        gh release create ${{ env.tag }} ${{ inputs.artifact }}
