name: Release Build
run-name: Release Build ${{ github.ref_name }}
on:
  push:
    tags: [ "release-*" ]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Make Artifact
        run: make
      - name: Archive Artifact
        run: tar -cvzf bin.tar.gz bin
      - name: Release Artifact
        run: gh release create "$GITHUB_REF_NAME" bin.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}
